

FROM mcr.microsoft.com/devcontainers/python:1-3.13

WORKDIR /workspaces

# Setup code
ARG GITHUB_TOKEN
RUN echo "Token value: [${GITHUB_TOKEN}]"
RUN if [ -z "${GITHUB_TOKEN}" ]; then echo "TOKEN IS EMPTY"; else echo "TOKEN HAS VALUE"; fi
RUN git clone --depth 1 https://${GITHUB_TOKEN}:x-oauth-basic@github.com/cantupaz/Modelo720 /workspaces/Modelo720


RUN pip3 install uv

USER vscode
ENV VIRTUAL_ENV="/home/vscode/.local/os-venv"
RUN uv venv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

# Install dev dependencies
WORKDIR /workspaces/Modelo720
RUN uv pip install -r requirements.txt




# Install library in editable mode
# COPY pyproject.toml MANIFEST.in /workspaces/
# RUN pip install -e /workspaces

WORKDIR /workspaces

# Set the default shell to bash instead of sh
ENV SHELL /bin/bash

# Default command runs tests
# CMD ["pytest"]
