# must run with docker build --build-arg GITHUB_TOKEN=your_token_here -t option-screener-dev .


FROM mcr.microsoft.com/devcontainers/python:1-3.11

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

# Uninstall pre-installed formatting and linting tools
# They would conflict with our pinned versions
# RUN \
#     pipx uninstall pydocstyle \
#     && pipx uninstall pycodestyle \
#     && pipx uninstall mypy \
#     && pipx uninstall pylint

RUN \
    curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - \
    && apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        # Additional library needed by some tests and accordingly by VScode Tests Discovery
        git \
        cmake \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Install uv
RUN pip3 install uv

WORKDIR /usr/src

# Setup code
ARG GITHUB_TOKEN
RUN echo "Token value: [${GITHUB_TOKEN}]"
RUN if [ -z "${GITHUB_TOKEN}" ]; then echo "TOKEN IS EMPTY"; else echo "TOKEN HAS VALUE"; fi
RUN git clone --depth 1 https://${GITHUB_TOKEN}:x-oauth-basic@github.com/cantupaz/Modelo720

RUN sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq && sudo chmod +x /usr/bin/yq


USER vscode
ENV VIRTUAL_ENV="/home/vscode/.local/os-venv"
RUN uv venv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

WORKDIR /tmp

# Install Python dependencies from requirements
COPY requirements.txt ./
RUN uv pip install -r requirements.txt

WORKDIR /workspaces

# Set the default shell to bash instead of sh
ENV SHELL /bin/bash
